version: 2
updates:
- package-ecosystem: yarn
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.36
    - 14.14.41
    - 15.0.0
  - dependency-name: postcss
    versions:
    - 8.2.12
  - dependency-name: date-fns
    versions:
    - 2.20.1
    - 2.20.3
  - dependency-name: classnames
    versions:
    - 2.3.0
  - dependency-name: next
    versions:
    - 10.1.1
    - 10.1.2
